# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ai_copilot.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'ai_copilot.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x61i_copilot.proto\x12\nai_copilot\"J\n\x0bThreatQuery\x12\r\n\x05query\x18\x01 \x01(\t\x12\x12\n\nquery_type\x18\x02 \x01(\t\x12\x18\n\x10investigation_id\x18\x03 \x01(\t\"U\n\x16ThreatAnalysisResponse\x12\x10\n\x08\x61nalysis\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x15\n\rmitre_tactics\x18\x03 \x03(\t\"=\n\x12\x43orrelationRequest\x12\x12\n\nentity_ids\x18\x01 \x03(\t\x12\x13\n\x0btime_window\x18\x02 \x01(\t\"I\n\x13\x43orrelationResponse\x12\x1e\n\x16\x63orrelation_graph_data\x18\x01 \x01(\t\x12\x12\n\nrisk_score\x18\x02 \x01(\x02\x32\xb6\x01\n\x10\x41ICopilotService\x12N\n\rAnalyzeThreat\x12\x17.ai_copilot.ThreatQuery\x1a\".ai_copilot.ThreatAnalysisResponse\"\x00\x12R\n\rCorrelateData\x12\x1e.ai_copilot.CorrelationRequest\x1a\x1f.ai_copilot.CorrelationResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ai_copilot_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_THREATQUERY']._serialized_start=32
  _globals['_THREATQUERY']._serialized_end=106
  _globals['_THREATANALYSISRESPONSE']._serialized_start=108
  _globals['_THREATANALYSISRESPONSE']._serialized_end=193
  _globals['_CORRELATIONREQUEST']._serialized_start=195
  _globals['_CORRELATIONREQUEST']._serialized_end=256
  _globals['_CORRELATIONRESPONSE']._serialized_start=258
  _globals['_CORRELATIONRESPONSE']._serialized_end=331
  _globals['_AICOPILOTSERVICE']._serialized_start=334
  _globals['_AICOPILOTSERVICE']._serialized_end=516
# @@protoc_insertion_point(module_scope)
