import { NextRequest, NextResponse } from "next/server";
import { connectDB } from "@/db";
import { ActivityLog } from "@/db/schema";
import { verifyToken } from "@/lib/auth";
import { LoginSchema } from "@/lib/validations";

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const parsed = LoginSchema.safeParse(body);
    if (!parsed.success) {
      return NextResponse.json({ error: parsed.error.issues[0].message }, { status: 400 });
    }
    const { username, password } = parsed.data;

    // Route authentication through API Gateway / user-service
    const GATEWAY_URL = process.env.GATEWAY_URL || "http://127.0.0.1:4000";
    let token = "";
    
    try {
      const gatewayRes = await fetch(`${GATEWAY_URL}/api/auth/login`, {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ username, password }),
        signal: AbortSignal.timeout(5000), // 5-second timeout
      });

      if (!gatewayRes.ok) {
        const errData = await gatewayRes.json().catch(() => ({}));
        return NextResponse.json({ error: errData.error || "Authentication failed" }, { status: gatewayRes.status });
      }

      const data = await gatewayRes.json();
      token = data.token;
    } catch (e) {
      console.error("Gateway auth call failed:", e);
      return NextResponse.json({ error: "Authentication service is temporarily unavailable" }, { status: 503 });
    }

    if (!token) {
      return NextResponse.json({ error: "Invalid credentials" }, { status: 401 });
    }

    // Verify and decode token locally using shared secret to retrieve profile info
    const payload = await verifyToken(token);
    if (!payload) {
      return NextResponse.json({ error: "Invalid token generated by authentication service" }, { status: 401 });
    }

    // Connect DB to log activity locally
    try {
      await connectDB();
      await ActivityLog.create({
        userId: payload.userId,
        action: "LOGIN",
        resource: "auth",
        ipAddress: req.headers.get("x-forwarded-for") || "unknown",
      });
    } catch (dbErr) {
      console.warn("Could not log login activity to database:", dbErr);
    }

    const response = NextResponse.json({
      success: true,
      user: {
        id: payload.userId,
        username: payload.username,
        email: payload.email,
        role: payload.role,
      },
    });

    const isProduction = process.env.NODE_ENV === "production";
    const isHttps = req.nextUrl.protocol === "https:" || req.headers.get("x-forwarded-proto") === "https";

    response.cookies.set("osint_token", token, {
      httpOnly: true,
      secure: isProduction || isHttps,
      sameSite: "strict", // Hardened SameSite rule
      maxAge: 60 * 60 * 24, // 24 hours persistent cookie
      path: "/",
    });

    return response;
  } catch (error) {
    console.error("Login error:", error);
    return NextResponse.json({ error: "Internal server error" }, { status: 500 });
  }
}
